#[î‚¶](#3054fa)\
format = """
$status\
$time\
[î‚°](fg:#3C4251 bg:#3054fa)\
$username\
[î‚°](bg:#3C4251 fg:#3054fa)\
$directory\
[î‚°](fg:#3C4251 bg:#23262f)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$container\
$terraform\
$python\
[î‚°](fg:#23262f bg:#7129ff)\
$git_branch\
$git_status\
[î‚° ](fg:#7129ff)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
add_newline = false

[status]
disabled = false
success_symbol = " "
format = "[$symbol]($style)"
style = "bg:#3C4251"

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#3054fa"
style_root = "bg:#3054fa"
format = '[$user]($style)'

[directory]
style = "bg:#3C4251"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "â€¦"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
style = "bg:#23262f"
format = '[  $symbol ($version)]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#23262f"
format = '[  $symbol ($version)]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#23262f"
format = '[  $symbol ($version)]($style)'

[git_branch]
symbol = "î‚ "
style = "bg:#7129ff"
format = '[$symbol$branch ]($style)'


[git_status]
#conflicted = "âš”ï¸ "
#ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
#behind = "ğŸ¢ Ã—${count}"
#diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
#untracked = "ğŸ›¤ï¸  Ã—${count}"
#stashed = "ğŸ“¦ "
#modified = "ğŸ“ Ã—${count}"
#staged = "ğŸ—ƒï¸  Ã—${count}"
#renamed = "ğŸ“› Ã—${count}"
#deleted = "ğŸ—‘ï¸  Ã—${count}"
conflicted="="	
ahead="${count}â‡¡"	
behind="${count}â‡£"	
diverged="${count}â‡•"	
up_to_date=""
untracked="${count}?"	
stashed="$"
modified="${count}!"	
staged="${count}+"
renamed= "${count}Â»"
deleted=	"${count}âœ˜"
style = "bg:#7129ff"
format = '[$all_status$ahead_behind ]($style)'

[golang]
style = "bg:#23262f"
format = '[ $symbol ($version)]($style)'

[java]
symbol = "â˜•"
style = "bg:#23262f"
format = '[ $symbol ($version)]($style)'

[python]
style = "bg:#23262f"
format = '[ $symbol ($version)]($style)'

[nodejs]
style = "bg:#23262f"
format = '[ $symbol ($version)]($style)'

[nim]
style = "bg:#23262f"
format = '[ $symbol ($version)]($style)'

[time]
disabled = false
time_format = "%T" #
style = "bg:#3C4251"
format = '[ $time]($style)'
